/** @spark/protocol——Spark 唯一合同（doc/02 §4）；跨包只允许 import 本入口，禁止深路径 */
export * from './ids.js'
export * from './primitives.js'
export * from './events.js'
export * from './extend.js'
export * from './api.js'
export * from './pair-link.js'
export * from './transport.js'
export * from './transport-node.js'
export * from './error-copy.js'
export * from './ui-copy.js'
export * from './format.js'
export * from './apply-event.js'
export * from './flow-rows.js'
export * from './context-usage.js'
export * from './keymap.js'
export * from './commands.js'
export * from './schema.js'
